### ISSUE TITLE
Add policies for su

### ISSUE THREAD

**Issue by slifox** [phhusson/super-bootimg#1]
su appears to use these permissions during boot (before any use). These should probably be added to the default set

```
allow init su_daemon process "siginh rlimitinh noatsecure"
allow su dalvikcache_data_file dir "write add_name remove_name"
allow su dalvikcache_data_file file "write create unlink"
allow su su capability "sys_nice dac_override"
allow system_server su binder "call"
```

In addition, I sometimes see these permissions come up when Superuser.apk grants access to a requesting app. However, often they don't show up. I'm not sure when/if they are actually needed:

```
allow su su unix_stream_socket "write"
allow su_daemon su_daemon process "signal"
allow su_daemon su_daemon unix_stream_socket "connect"
```

**Comment by phhusson** [comment]
siginh/rlimitinh/noatsecure are not needed (though they need to be put in noaudit, which currently... allows)

In which case did you need dalvikcache_data_file write?
I think that it is needed only for first call ever to am. And I'd rather NOT give su the right to overload apps' dexes.

I doubt sys_nice is needed, but it is not a problem, and useful.
I know we need dac_override because of /dev/pts, but dac_override is too powerful.
I think I already have it enabled with a big warning in the code.

su doing binder calls to system_server is fine I think (so it means unrestricted access to all system_server commands)

For sockets/signals, they are ok.

I'm a bit suprised by your results, I think I already have most of those changes. Anyway, I'll check, and if they aren't there, I'll implement them as I said.

**Comment by phhusson** [comment]
shell doesn't have write access to dalvikcache_data_file, so it's a no for those.
